### ISSUE TITLE
Failing when getting service from DI container

### ISSUE THREAD

**Issue by larsbloch** [Battle-Line-Productions/EmailValidator#9] opened 2023-09-05 10:57 UTC
I get an error when trying to get the emailvalidator instance from DI container. I gives me the error FileNotFound _disposableEmailFile

Using dot net 7 and hot chocolate Gql Api.

<img width="362" alt="image" src="https://github.com/Battle-Line-Productions/EmailValidator/assets/17157846/59ae8d43-17f1-4855-aa36-734d526bd240">

Btw this library is just what i was looking for. it is awesome. Thanks for sharing it !

**Comment by funkel1989** [comment] 2023-09-05 11:04
Can you please provide a minimal reproduction where this issue happens?  I'm unable to reproduce it.

Thanks!

**Comment by larsbloch** [comment] 2023-09-05 11:09
@funkel1989 

I have just been looking at your code. Could it be this part in the disposableValidator
https://github.com/Battle-Line-Productions/EmailValidator/blob/main/AdvancedEmailValidator/Validators/DisposableValidator.cs

I dont have a physical file.

    public DisposableValidator(IFileReader fileReader)
    {
        _fileReader = fileReader;

        if (!_fileReader.Exists(_disposableEmailFile))
        {
            throw new FileNotFoundException(nameof(_disposableEmailFile));
        }
    }

**Comment by funkel1989** [comment] 2023-09-05 12:34
@larsbloch that is it, but I have a dependencies handle script that is supposed to download the disposable list from github. 
https://github.com/Battle-Line-Productions/EmailValidator/blob/main/AdvancedEmailValidator/BuildDependencies.cs

that gets called from the constructor here: 
https://github.com/Battle-Line-Productions/EmailValidator/blob/main/AdvancedEmailValidator/EmailValidator.cs#L42

it saves as a file on the local drive. Are you possibly running from a container or a solution that doesn't have storage that may otherwise cause this to fail?

**Comment by larsbloch** [comment] 2023-09-05 12:46
Right now im just debugging my project locally, so no container. Its a standard asp core project with hot chocolate graphql library. I will try and investigate if that file exists and see why its not used or downloaded.

**Comment by funkel1989** [comment] 2023-09-05 12:53
Let me know if you discover anything. I have an example project in the repo that is dotnet 7. Start that up and run it and see if it downloads the file to the example project. that will tell you if your issue is local or not, as the example works on other machines i've tried it on.

**Comment by larsbloch** [comment] 2023-09-05 13:15
@funkel1989 

The sample app is working, and correctly downloading the file. 
but the samplewebapi is giving me the same error. I have deleted the file from before but i can see it is never being downloaded when running the samplewebapi

Somehow the BuildDependencies methods you mentioned are never being run. I tried adding breakpoints but they are not hit

<img width="506" alt="image" src="https://github.com/Battle-Line-Productions/EmailValidator/assets/17157846/1f6213e2-630e-489f-9c7d-08e996fec799">

**Comment by funkel1989** [comment] 2023-09-05 13:50
I'll work on this later today and get back to you. In the mean time you can disable disposable check when passing in a validationOptions and continue forward.

**Comment by larsbloch** [comment] 2023-09-05 14:14
@funkel1989 
Allright. I could also have debugged it futher but unfortunately im out of time for today.
The error happens when instantiating the class so i dont event get to the validateoptions part.

**Comment by funkel1989** [comment] 2023-09-06 01:52
@larsbloch a fix for this is published to nuget as version 2.2.1. Please pull the new version and let me know if your still encountering the issue.

**Comment by larsbloch** [comment] 2023-09-06 07:19
Everything seems to work as inteded. Thanks for the quick fix.
Im working in a small startup and some of our testusers have invited emails that does not exist or have mispellings. I have been looking at other libraries but this seems to be complete to what is needed to validate an email. Thanks for making this.

I will let you know if i experience other issues and feel free to reach out if you need feedback.

**Closed as completed** 2023-09-06 12:46 UTC
Labels: bug
